const express = require('express')
const router = express.Router()
const { getSingleTask, getAllTasks, createTask, updateSingleTask, deleteSingleTask, deleteAllTasks } = require('../controllers/tasks')
router.get('/', getAllTasks)
router.post('/', createTask)
router.get('/:id', getSingleTask)
router.delete('/', deleteAllTasks)
router.delete('/:id', deleteSingleTask)
router.patch('/:id', updateSingleTask)